name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main # Se ejecuta cuando hay cambios en la rama "main"
  workflow_dispatch: # Permite ejecutar manualmente el deploy desde GitHub

permissions:
  contents: read

jobs:
  build-and-deploy:
    permissions:
      contents: write # Permiso para escribir en el repositorio
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
